export const humanModelConfig = {
  modelPath: '/models/final%20low%20poly%20character%20rigged.glb',
  initial: {
    fitHeight: 2.65,
    rotation: [0, 0, 0] as [number, number, number],
    position: [0, -1.25, 0] as [number, number, number],
  },
  cameraTargets: {
    perspective: { position: [0.7, 1.25, 4.2], target: [0, 0.55, 0] },
    front: { position: [0, 0.85, 4.35], target: [0, 0.55, 0] },
    side: { position: [4.35, 0.85, 0], target: [0, 0.55, 0] },
    top: { position: [0, 5.0, 0.05], target: [0, 0.2, 0] },
  },
  focusTargets: {
    general: [0, 0.55, 0],
    neck: [0, 1.55, 0],
    trunk: [0, 0.85, 0],
    upperArmLeft: [-0.55, 1.2, 0],
    upperArmRight: [0.55, 1.2, 0],
    lowerArmLeft: [-0.78, 0.85, 0.05],
    lowerArmRight: [0.78, 0.85, 0.05],
    wristLeft: [-0.95, 0.56, 0.08],
    wristRight: [0.95, 0.56, 0.08],
    hipLeft: [-0.28, 0.05, 0],
    hipRight: [0.28, 0.05, 0],
    kneeLeft: [-0.28, -0.72, 0],
    kneeRight: [0.28, -0.72, 0],
    ankleLeft: [-0.28, -1.18, 0.08],
    ankleRight: [0.28, -1.18, 0.08],
    legs: [0, -0.55, 0],
  },
  // Put exact GLB bone names here after checking the browser console table.
  explicitBones: {
    neck: '',
    head: '',
    trunk: '',
    chest: '',
    shoulderLeft: '',
    shoulderRight: '',
    upperArmLeft: '',
    upperArmRight: '',
    lowerArmLeft: '',
    lowerArmRight: '',
    wristLeft: '',
    wristRight: '',
    handLeft: '',
    handRight: '',
    hipLeft: '',
    hipRight: '',
    kneeLeft: '',
    kneeRight: '',
    ankleLeft: '',
    ankleRight: '',
  },
  // Fallback aliases used only when explicitBones is blank.
  boneAliases: {
    neck: ['neck', 'cuello', 'mixamorigneck', 'spine003', 'spine.003'],
    head: ['head', 'cabeza', 'mixamorighead'],
    trunk: ['spine', 'spine1', 'spine2', 'chest', 'torso', 'trunk', 'columna', 'mixamorigspine', 'mixamorigspine1', 'mixamorigspine2'],
    chest: ['chest', 'spine2', 'spine.002', 'upperchest', 'mixamorigspine2'],
    shoulderLeft: ['leftshoulder', 'shoulder_l', 'l_shoulder', 'clavicle_l', 'mixamorigleftshoulder'],
    shoulderRight: ['rightshoulder', 'shoulder_r', 'r_shoulder', 'clavicle_r', 'mixamorigrightshoulder'],
    upperArmLeft: ['leftarm', 'upper_arm_l', 'l_upperarm', 'brazo_l', 'mixamorigleftarm'],
    upperArmRight: ['rightarm', 'upper_arm_r', 'r_upperarm', 'brazo_r', 'mixamorigrightarm'],
    lowerArmLeft: ['leftforearm', 'forearm_l', 'lower_arm_l', 'antebrazo_l', 'mixamorigleftforearm'],
    lowerArmRight: ['rightforearm', 'forearm_r', 'lower_arm_r', 'antebrazo_r', 'mixamorigrightforearm'],
    wristLeft: ['lefthand', 'hand_l', 'wrist_l', 'mano_l', 'mixamoriglefthand'],
    wristRight: ['righthand', 'hand_r', 'wrist_r', 'mano_r', 'mixamorigrighthand'],
    handLeft: ['lefthand', 'hand_l', 'mano_l', 'mixamoriglefthand'],
    handRight: ['righthand', 'hand_r', 'mano_r', 'mixamorigrighthand'],
    hipLeft: ['leftupleg', 'thigh_l', 'upper_leg_l', 'cadera_l', 'mixamorigleftupleg'],
    hipRight: ['rightupleg', 'thigh_r', 'upper_leg_r', 'cadera_r', 'mixamorigrightupleg'],
    kneeLeft: ['leftleg', 'shin_l', 'calf_l', 'rodilla_l', 'mixamorigleftleg'],
    kneeRight: ['rightleg', 'shin_r', 'calf_r', 'rodilla_r', 'mixamorigrightleg'],
    ankleLeft: ['leftfoot', 'foot_l', 'tobillo_l', 'mixamorigleftfoot'],
    ankleRight: ['rightfoot', 'foot_r', 'tobillo_r', 'mixamorigrightfoot'],
  },
  // Editable local-axis rotations. Use browser debug panel if an axis/sign must be inverted.
  joints: {
    neckFlexion: { bone: 'neck', axis: 'x', sign: 1, offset: 0, min: -30, max: 60, side: 'center' },
    trunkFlexion: { bone: 'trunk', axis: 'x', sign: 0.55, offset: 0, min: 0, max: 90, side: 'center' },
    upperArmFlexionLeft: { bone: 'upperArmLeft', axis: 'x', sign: -1, offset: 0, min: -45, max: 140, side: 'left' },
    upperArmFlexionRight: { bone: 'upperArmRight', axis: 'x', sign: -1, offset: 0, min: -45, max: 140, side: 'right' },
    upperArmAbductionLeft: { bone: 'upperArmLeft', axis: 'z', sign: -1, offset: 0, min: 0, max: 45, side: 'left' },
    upperArmAbductionRight: { bone: 'upperArmRight', axis: 'z', sign: 1, offset: 0, min: 0, max: 45, side: 'right' },
    lowerArmFlexionLeft: { bone: 'lowerArmLeft', axis: 'x', sign: -1, offset: 0, min: 20, max: 150, side: 'left' },
    lowerArmFlexionRight: { bone: 'lowerArmRight', axis: 'x', sign: -1, offset: 0, min: 20, max: 150, side: 'right' },
    wristFlexionLeft: { bone: 'wristLeft', axis: 'x', sign: -1, offset: 0, min: -45, max: 60, side: 'left' },
    wristFlexionRight: { bone: 'wristRight', axis: 'x', sign: -1, offset: 0, min: -45, max: 60, side: 'right' },
    wristDeviationLeft: { bone: 'wristLeft', axis: 'z', sign: -1, offset: 0, min: 0, max: 30, side: 'left' },
    wristDeviationRight: { bone: 'wristRight', axis: 'z', sign: 1, offset: 0, min: 0, max: 30, side: 'right' },
    hipFlexionLeft: { bone: 'hipLeft', axis: 'x', sign: 1, offset: 0, min: 0, max: 90, side: 'left' },
    hipFlexionRight: { bone: 'hipRight', axis: 'x', sign: 1, offset: 0, min: 0, max: 90, side: 'right' },
    kneeFlexionLeft: { bone: 'kneeLeft', axis: 'x', sign: 1, offset: 0, min: 0, max: 120, side: 'left' },
    kneeFlexionRight: { bone: 'kneeRight', axis: 'x', sign: 1, offset: 0, min: 0, max: 120, side: 'right' },
    ankleFlexionLeft: { bone: 'ankleLeft', axis: 'x', sign: 1, offset: 0, min: -30, max: 45, side: 'left' },
    ankleFlexionRight: { bone: 'ankleRight', axis: 'x', sign: 1, offset: 0, min: -30, max: 45, side: 'right' },
  },
};
