export const humanModelConfig = {
  modelPath: '/public/models/final low poly character rigged.glb',
  initial: {
    fitHeight: 2.65,
    rotation: [0, 0, 0] as [number, number, number],
    position: [0, -1.25, 0] as [number, number, number],
  },
  cameraTargets: {
    perspective: { position: [0.7, 1.25, 4.2], target: [0, 0.55, 0] },
    front: { position: [0, 0.85, 4.35], target: [0, 0.55, 0] },
    side: { position: [4.35, 0.85, 0], target: [0, 0.55, 0] },
    top: { position: [0, 5.0, 0.05], target: [0, 0.2, 0] },
  },
  focusTargets: {
    general: [0, 0.55, 0],
    neck: [0, 1.55, 0],
    trunk: [0, 0.85, 0],
    upperArmLeft: [-0.55, 1.2, 0],
    upperArmRight: [0.55, 1.2, 0],
    lowerArmLeft: [-0.78, 0.85, 0.05],
    lowerArmRight: [0.78, 0.85, 0.05],
    wristLeft: [-0.95, 0.56, 0.08],
    wristRight: [0.95, 0.56, 0.08],
    legs: [0, -0.55, 0],
  },
  // Aliases are intentionally broad because Blender/GLB rigs often use Mixamo, Blender or custom names.
  boneAliases: {
    neck: ['neck', 'cuello', 'mixamorigneck', 'spine003', 'spine.003'],
    trunk: ['spine', 'spine1', 'spine2', 'chest', 'torso', 'trunk', 'columna', 'mixamorigspine', 'mixamorigspine1', 'mixamorigspine2'],
    shoulderLeft: ['leftshoulder', 'shoulder_l', 'l_shoulder', 'clavicle_l', 'mixamorigleftshoulder'],
    shoulderRight: ['rightshoulder', 'shoulder_r', 'r_shoulder', 'clavicle_r', 'mixamorigrightshoulder'],
    upperArmLeft: ['leftarm', 'upper_arm_l', 'l_upperarm', 'brazo_l', 'mixamorigleftarm'],
    upperArmRight: ['rightarm', 'upper_arm_r', 'r_upperarm', 'brazo_r', 'mixamorigrightarm'],
    lowerArmLeft: ['leftforearm', 'forearm_l', 'lower_arm_l', 'antebrazo_l', 'mixamorigleftforearm'],
    lowerArmRight: ['rightforearm', 'forearm_r', 'lower_arm_r', 'antebrazo_r', 'mixamorigrightforearm'],
    wristLeft: ['lefthand', 'hand_l', 'wrist_l', 'mano_l', 'mixamoriglefthand'],
    wristRight: ['righthand', 'hand_r', 'wrist_r', 'mano_r', 'mixamorigrighthand'],
    hipLeft: ['leftupleg', 'thigh_l', 'upper_leg_l', 'cadera_l', 'mixamorigleftupleg'],
    hipRight: ['rightupleg', 'thigh_r', 'upper_leg_r', 'cadera_r', 'mixamorigrightupleg'],
    kneeLeft: ['leftleg', 'shin_l', 'calf_l', 'rodilla_l', 'mixamorigleftleg'],
    kneeRight: ['rightleg', 'shin_r', 'calf_r', 'rodilla_r', 'mixamorigrightleg'],
    ankleLeft: ['leftfoot', 'foot_l', 'tobillo_l', 'mixamorigleftfoot'],
    ankleRight: ['rightfoot', 'foot_r', 'tobillo_r', 'mixamorigrightfoot'],
  },
  // Editable rig axis/inversion map. Change signs here if a custom rig bends in the opposite direction.
  rotations: {
    neck: { axis: 'x', sign: 1 },
    trunk: { axis: 'x', sign: 1 },
    upperArmFlexion: { axis: 'x', sign: -1 },
    upperArmAbductionLeft: { axis: 'z', sign: -1 },
    upperArmAbductionRight: { axis: 'z', sign: 1 },
    lowerArmFlexionLeft: { axis: 'x', sign: -1 },
    lowerArmFlexionRight: { axis: 'x', sign: -1 },
    wristFlexion: { axis: 'x', sign: -1 },
    wristDeviationLeft: { axis: 'z', sign: -1 },
    wristDeviationRight: { axis: 'z', sign: 1 },
    kneeFlexion: { axis: 'x', sign: 1 },
  },
};
