import { useEffect, useRef } from 'react';
import * as THREE from 'three';
import type { BodySide, RulaPosture } from '../types/rula';

interface Props { posture: RulaPosture; activeKey: string; activeSide: BodySide; onResetFocus: () => void; }
const deg = THREE.MathUtils.degToRad;
const sideSign = (side: BodySide) => side === 'left' ? -1 : 1;
const colors = { body: '#b9d7f0', active: '#2b6cb0', joint: '#f6ad55', guide: '#718096', left: '#68d391', right: '#63b3ed' };

function mat(color: string) { return new THREE.MeshStandardMaterial({ color, roughness: 0.58, metalness: 0.04 }); }
function capsule(length: number, radius: number, color: string, active: boolean) { const mesh = new THREE.Mesh(new THREE.CapsuleGeometry(radius, length, 12, 24), mat(active ? colors.active : color)); mesh.position.y = -length / 2; mesh.castShadow = true; return mesh; }
function joint(radius: number, active: boolean) { return new THREE.Mesh(new THREE.SphereGeometry(radius, 24, 24), mat(active ? colors.active : colors.joint)); }
function line(points: THREE.Vector3[], color: string) { const geometry = new THREE.BufferGeometry().setFromPoints(points); const material = new THREE.LineBasicMaterial({ color }); return new THREE.Line(geometry, material); }
function textSprite(text: string) { const canvas = document.createElement('canvas'); canvas.width = 320; canvas.height = 64; const ctx = canvas.getContext('2d')!; ctx.fillStyle = 'rgba(255,255,255,.94)'; ctx.strokeStyle = '#bee3f8'; ctx.lineWidth = 4; ctx.roundRect(4, 8, 312, 48, 20); ctx.fill(); ctx.stroke(); ctx.fillStyle = '#2b6cb0'; ctx.font = 'bold 26px Inter, Arial'; ctx.fillText(text, 20, 42); const texture = new THREE.CanvasTexture(canvas); const sprite = new THREE.Sprite(new THREE.SpriteMaterial({ map: texture, transparent: true })); sprite.scale.set(0.65, 0.13, 1); return sprite; }
function angleArc(angle: number, label: string, side = 1, radius = 0.42) { const group = new THREE.Group(); const start = -Math.PI / 2; const end = start + deg(angle); const pts = Array.from({ length: 33 }, (_, i) => { const t = start + (end - start) * (i / 32); return new THREE.Vector3(side * Math.cos(t) * radius, Math.sin(t) * radius, 0.02); }); group.add(line(pts, colors.active)); group.add(line([new THREE.Vector3(0,0,0), new THREE.Vector3(0,-radius,0)], colors.guide)); const labelSprite = textSprite(`${label}: ${Math.round(angle)}°`); labelSprite.position.set(side * radius * .9, -radius * .25, .04); group.add(labelSprite); return group; }

function createModel(posture: RulaPosture, activeKey: string, activeSide: BodySide) {
  const root = new THREE.Group(); root.position.y = -0.85;
  const trunkGroup = new THREE.Group(); trunkGroup.rotation.set(deg(posture.trunkFlexion), 0, deg(posture.trunkSideBent ? 8 : 0)); root.add(trunkGroup);
  const trunk = capsule(0.82, 0.21, colors.body, activeKey === 'trunk'); trunk.position.y = 1.08; trunkGroup.add(trunk); if (activeKey === 'trunk') trunkGroup.add(angleArc(posture.trunkFlexion, 'Tronco', 1, .55));
  const neckGroup = new THREE.Group(); neckGroup.position.y = 1.62; neckGroup.rotation.set(deg(posture.neckFlexion), deg(posture.neckRotated ? 18 : 0), deg(posture.neckSideBent ? 12 : 0)); trunkGroup.add(neckGroup); neckGroup.add(capsule(.18,.045,'#a0aec0',activeKey==='neck')); const head = new THREE.Mesh(new THREE.SphereGeometry(.17,32,32), mat('#edf2f7')); head.position.y=.17; neckGroup.add(head); if(activeKey==='neck') neckGroup.add(angleArc(posture.neckFlexion,'Cuello',1,.32));
  (['left','right'] as BodySide[]).forEach((side)=>{ const s=sideSign(side); const p=posture[side]; const armRoot=new THREE.Group(); armRoot.position.set(s*.48,1.55,0); trunkGroup.add(armRoot); const isActiveSide=side===activeSide; const active=(k:string)=>isActiveSide && activeKey===k; armRoot.add(joint(.09,active('upperArm'))); const upper=new THREE.Group(); upper.rotation.set(deg(p.upperArmFlexion),0,deg(-s*(p.upperArmAbducted?22:6))); armRoot.add(upper); upper.add(capsule(.56,.055,side==='left'?colors.left:colors.right,active('upperArm'))); if(active('upperArm')) upper.add(angleArc(p.upperArmFlexion,'Brazo',s)); const lower=new THREE.Group(); lower.position.y=-.56; lower.rotation.set(deg(180-p.lowerArmFlexion),0,deg(s*(p.lowerArmAcrossMidline?18:p.lowerArmOutToSide?-18:0))); upper.add(lower); lower.add(joint(.07,active('lowerArm'))); lower.add(capsule(.48,.045,'#c6f6d5',active('lowerArm'))); if(active('lowerArm')) lower.add(angleArc(p.lowerArmFlexion,'Antebrazo',s,.28)); const wrist=new THREE.Group(); wrist.position.y=-.48; wrist.rotation.set(deg(p.wristFlexion),0,deg(s*(p.wristDeviation?18:0))); lower.add(wrist); wrist.add(joint(.055,active('wrist'))); wrist.add(capsule(.2,.04,'#fefcbf',active('wrist'))); if(active('wrist')) wrist.add(angleArc(p.wristFlexion,'Muñeca',s,.2)); });
  const legsRoot = new THREE.Group(); legsRoot.position.y = .63; root.add(legsRoot); (['left','right'] as BodySide[]).forEach((side)=>{ const s=sideSign(side); const thigh=new THREE.Group(); thigh.position.x=s*.16; thigh.rotation.set(deg(posture.legSupport==='seatedSupported'?78:8),0,deg(s*4)); legsRoot.add(thigh); thigh.add(capsule(.58,.065,'#bee3f8',activeKey==='legs')); const shin=new THREE.Group(); shin.position.y=-.58; shin.rotation.x=deg(posture.legSupport==='seatedSupported'?-70:5); thigh.add(shin); shin.add(capsule(.58,.055,'#e6fffa',activeKey==='legs')); });
  const grid = new THREE.GridHelper(4,8,'#cbd5e0','#edf2f7'); root.add(grid); return root;
}

export default function HumanModel({ posture, activeKey, activeSide, onResetFocus }: Props) {
  const host = useRef<HTMLDivElement>(null); const refs = useRef<{scene:THREE.Scene; camera:THREE.PerspectiveCamera; renderer:THREE.WebGLRenderer; model?:THREE.Group; raf?:number; target:THREE.Vector3; dragging:boolean; lastX:number; yaw:number} | null>(null);
  useEffect(()=>{ const el=host.current!; const scene=new THREE.Scene(); scene.background=new THREE.Color('#ffffff'); const camera=new THREE.PerspectiveCamera(42, el.clientWidth/el.clientHeight, .1, 100); camera.position.set(0,.4,3.8); const renderer=new THREE.WebGLRenderer({antialias:true}); renderer.setPixelRatio(Math.min(window.devicePixelRatio,2)); renderer.setSize(el.clientWidth,el.clientHeight); renderer.shadowMap.enabled=true; el.appendChild(renderer.domElement); scene.add(new THREE.AmbientLight('#ffffff',.8)); const dl=new THREE.DirectionalLight('#ffffff',1.2); dl.position.set(3,4,4); dl.castShadow=true; scene.add(dl); refs.current={scene,camera,renderer,target:new THREE.Vector3(0,.1,0),dragging:false,lastX:0,yaw:0}; const down=(e:PointerEvent)=>{refs.current!.dragging=true; refs.current!.lastX=e.clientX}; const move=(e:PointerEvent)=>{const r=refs.current!; if(r.dragging){r.yaw+=(e.clientX-r.lastX)*.006; r.lastX=e.clientX;}}; const up=()=>{refs.current!.dragging=false}; renderer.domElement.addEventListener('pointerdown',down); window.addEventListener('pointermove',move); window.addEventListener('pointerup',up); const resize=()=>{camera.aspect=el.clientWidth/el.clientHeight; camera.updateProjectionMatrix(); renderer.setSize(el.clientWidth,el.clientHeight)}; window.addEventListener('resize',resize); const tick=()=>{const r=refs.current!; const focus:Record<string,THREE.Vector3>={upperArm:new THREE.Vector3(sideSign(activeSide)*.55,.65,.15),lowerArm:new THREE.Vector3(sideSign(activeSide)*.72,.24,.2),wrist:new THREE.Vector3(sideSign(activeSide)*.8,-.12,.24),neck:new THREE.Vector3(0,.95,.1),trunk:new THREE.Vector3(0,.25,.2),legs:new THREE.Vector3(0,-.75,.25),general:new THREE.Vector3(0,.1,0)}; const target=focus[activeKey]??focus.general; const dist=['wrist','lowerArm','upperArm','neck'].includes(activeKey)?2.05:activeKey==='general'?3.8:2.8; r.target.lerp(target,.08); const orbit=new THREE.Vector3(Math.sin(r.yaw)*dist,.45,Math.cos(r.yaw)*dist); camera.position.lerp(r.target.clone().add(orbit),.055); camera.lookAt(r.target); renderer.render(scene,camera); r.raf=requestAnimationFrame(tick)}; tick(); return()=>{const r=refs.current; if(!r)return; cancelAnimationFrame(r.raf!); renderer.domElement.removeEventListener('pointerdown',down); window.removeEventListener('pointermove',move); window.removeEventListener('pointerup',up); window.removeEventListener('resize',resize); el.removeChild(renderer.domElement); renderer.dispose(); refs.current=null;}; },[]);
  useEffect(()=>{ const r=refs.current; if(!r)return; if(r.model) r.scene.remove(r.model); r.model=createModel(posture,activeKey,activeSide); r.scene.add(r.model); },[posture,activeKey,activeSide]);
  return <div className="canvas-shell" ref={host}><button className="ghost floating" onClick={onResetFocus}>Vista general</button><span className="drag-help">Arrastra para rotar · zoom automático por región activa</span></div>;
}
